services:
  db:
    build:
      context: ./mongodb
      dockerfile: mongodb.dockerfile
    container_name: rg-profiler-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: benchmarkdbuser
      MONGO_INITDB_ROOT_PASSWORD: benchmarkdbpass
      MONGO_INITDB_DATABASE: hello_world
    # No need to expose ports externally, containers communicate within the network
    # ports:
    #   - "27017:27017"
    healthcheck:
      test: mongosh --quiet --eval 'db.runCommand("ping").ok' localhost:27017/admin -u benchmarkdbuser -p benchmarkdbpass || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped
    networks:
      - rg-profiler-network

networks:
  rg-profiler-network:
    external: true