services:
  db:
    build:
      context: ./postgres
      dockerfile: postgres.dockerfile
    container_name: rg-profiler-postgres
    environment:
      POSTGRES_USER: benchmarkdbuser
      POSTGRES_PASSWORD: benchmarkdbpass
      POSTGRES_DB: hello_world
    # No need to expose ports externally, containers communicate within the network
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U benchmarkdbuser -d hello_world"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks:
      - rg-profiler-network

networks:
  rg-profiler-network:
    external: true
