# Energy-focused configuration for measuring power consumption
mode: energy

# Test definitions - endpoints to test and their scripts
tests:
  - name: json_fixed
    endpoint: /json
    script: energy_json.lua
    description: "JSON serialization test for energy measurement"
    
  - name: plaintext_fixed
    endpoint: /plaintext
    script: energy_plaintext.lua
    description: "Plaintext response test for energy measurement"
    
  - name: db_fixed
    endpoint: /db
    script: energy_db.lua
    description: "Database query test for energy measurement"
    
  - name: template_fixed
    endpoint: /template-simple
    script: energy_template.lua
    description: "Simple template rendering test for energy measurement"
    
  - name: cpu_intensive
    endpoint: /cpu-intensive
    script: energy_cpu.lua
    description: "CPU-intensive computation test for energy measurement"
    
  - name: memory_heavy
    endpoint: /memory-heavy
    script: energy_memory.lua
    description: "Memory-intensive operation test for energy measurement"
    
  # New tests for enhanced energy measurement
  - name: middleware_fixed
    endpoint: /middleware-advanced
    script: energy_middleware.lua
    description: "Middleware chain test with fixed execution pattern for energy measurement"
    parameters:
      skip_security: false
      simulate_rate_limit: false
      transform_heavy: true
      transform_response: true
    
  - name: streaming_fixed
    endpoint: /streaming
    script: energy_streaming.lua
    description: "Streaming response test with fixed pattern for energy measurement"
    parameters:
      mode: json
      size: 2000
      chunk_size: 64
      delay: 0
      
  - name: error_handling_fixed
    endpoint: /errors
    script: energy_errors.lua
    description: "Error handling test with deterministic pattern for energy measurement"
    parameters:
      type: validation
      recovery: 5
      
  - name: routing_complex_fixed
    endpoint: /routing/123/users/filter/active/sort/name
    script: energy_routing.lua
    description: "Complex routing test with fixed pattern for energy measurement"
    parameters:
      complexity: 3
      delay: 0
      
  - name: mixed_workload_fixed
    endpoint: /mixed-workload
    script: energy_mixed.lua
    description: "Mixed workload with fixed execution pattern for energy measurement"
    parameters:
      pattern: balanced
      intensity: 3
      fixed_seed: true
      
  - name: io_operations_fixed
    endpoint: /io-ops
    script: energy_io.lua
    description: "File I/O operations with fixed patterns for energy measurement"
    parameters:
      op: combined
      buffer: 8192
      size: 1024
      iterations: 3
      sync: buffered

# Energy measurement settings
energy:
  # Number of runs for statistical significance
  runs: 1
  # Interval between runs in seconds
  run_interval: 10
  # Sampling frequency in seconds (lower = more frequent)
  sampling_frequency: 0.5
  # Tracking mode for energy measurements (process or machine)
  tracking_mode: "process"
  # Custom units for output
  units:
    energy: "Wh"    # Options: Wh, kWh, J, kJ
    co2: "mgCO2e"   # Options: mgCO2e, gCO2e, kgCO2e
    time: "s"       # Options: s, ms, min

# (CodeCarbon settings are defined via environment variables in container_manager.py)

# Profiling settings - Disabled for energy mode
profiling:
  scalene:
    enabled: false

# WRK settings optimized for reproducible energy measurements
wrk:
  # Longer duration for stable measurements
  duration: 45
  # No pipelining for consistent connection behavior
  pipeline: 1
  # Fixed concurrency - no ramping
  max_concurrency: 8
  # Single concurrency level
  levels: "8"
  # Connection timeout in seconds
  timeout: 10
  # Headers to include in requests
  headers:
    Accept: application/json
    Connection: keep-alive

# Server settings
server:
  # Minimal warmup time
  warmup_time: 5
  # More recovery between tests
  recovery_time: 10
  # Server startup timeout
  startup_timeout: 60
  # Post-startup stabilization
  stabilization_time: 5