# Quick test configuration for rapid validation
mode: quick

# Test definitions
tests:
  - name: json
    endpoint: /json
    script: json.lua
    description: "JSON serialization test for quick validation"

# Profiling settings
profiling:
  scalene:
    enabled: true
    profile_all: true
    reduced_profile: true  # Use reduced profiling for better overhead
    memory_sampling_rate: 100  # Memory sampling rate in Hz
    cpu_sampling_rate: 0.01  # CPU sampling rate in seconds

# Endpoints configuration
endpoints:
  include_all: false
  include: ["json"]

# Minimal WRK settings
wrk:
  # Very short duration
  duration: 1
  # No pipelining
  pipeline: 1
  # Single connection
  max_concurrency: 1
  # Single level
  levels: "1"
  # Short timeout
  timeout: 2
  # Basic headers
  headers:
    Accept: application/json
    Connection: keep-alive

# Minimal server settings
server:
  # No warmup
  warmup_time: 0
  # No recovery
  recovery_time: 0
  # Short startup timeout
  startup_timeout: 10
  # Minimal stabilization
  stabilization_time: 0.5

# Quick test variants
quick_variants:
  # Variant with no profiling for fastest testing
  test_only:
    profiling:
      scalene:
        enabled: false
    server:
      startup_timeout: 20
      stabilization_time: 1
    wrk:
      duration: 2