services:
  db:
    build:
      context: ./mysql
      dockerfile: mysql.dockerfile
    container_name: rg-profiler-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: benchmarkdbuser
      MYSQL_PASSWORD: benchmarkdbpass
      MYSQL_DATABASE: hello_world
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "benchmarkdbuser", "-pbenchmarkdbpass"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped
    networks:
      - rg-profiler-network

networks:
  rg-profiler-network:
    external: true