services:
  db:
    image: mongo:latest
    container_name: rg-profiler-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: benchmarkdbuser
      MONGO_INITDB_ROOT_PASSWORD: benchmarkdbpass
      MONGO_INITDB_DATABASE: hello_world
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet mongodb://benchmarkdbuser:benchmarkdbpass@localhost:27017/admin
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped
    networks:
      - rg-profiler-network

networks:
  rg-profiler-network:
    external: true